DROP TABLE IF EXISTS targets;
CREATE TABLE targets (
  address TEXT not NULL PRIMARY KEY,
  name TEXT not NULL,
  run BOOLEAN DEFAULT TRUE,
  running BOOLEAN DEFAULT FALSE,
  me BOOLEAN DEFAULT FALSE,
  stable BOOLEAN DEFAULT TRUE,
  responded BOOLEAN DEFAULT FALSE,
  sample_time INTEGER DEFAULT 0,
  total_count INTEGER DEFAULT 0,
  total_success INTEGER DEFAULT 0
);

